[project]
name = "morts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.0",
    "earthaccess>=0.18.0",
    "geopandas>=1.1.3",
    "lazycogs>=0.3.0",
    "matplotlib>=3.10.9",
    "numpy>=2.4.4",
    "obstore>=0.9.4",
    "pandas>=3.0.3",
    "pyproj>=3.7.2",
    "pystac-client>=0.9.0",
    "rasterio>=1.5.0",
    "rioxarray>=0.22.0",
    "rustac>=0.9.11",
    "scipy>=1.17.1",
    "sentinel-tiles>=1.1.1",
    "shapely>=2.1.2",
    "snakemake>=9.21.0",
    "stac-geoparquet>=0.7.0",
    "tqdm>=4.67.3",
    "xarray>=2026.4.0",
]
